### ISSUE TITLE
Docker dependancy

### ISSUE THREAD

**Issue by Thann** [HandyMiner/HandyBrowser#1]
Docker is an extremely powerful tool that is privileged to do just about anything. Allowing userspace apps to control docker is an extremely iIl advised security model. Most people will require `sudo` to run docker commands because anything else is installing a rootkit on your own computer. I like that you sandbox HSD, but I think it would be best to ask users to start the HSD container on their own, or just spawn it directly.

**Comment by smcki012** [comment]
Hey Thann!

We address this concern on the releases page: “Why sudo? Docker needs sudo permissions to run. Tinfoil hat on: Within the HandyBrowser Application, node.js is locked down to only file:// protocol (ie: the navigation tray layout/UI) and NOT anything coming in from the web. Any windows loaded over http/https will not have any permissions to node.js.”

If you see the readme, you’ll see the plan is to eventually move away from Docker. It’s moreso for simplicity with running the node/recursive resolver/and other WebRTC related stuff we have incoming. 

As far as UI/UX goes, the browser would never get any usage if a user had to spin a node up themselves first by adding manual steps to the process. It’s also not a UX flow browsers would opt to ever use, like Brave. This is a reference and anyone is allowed to clone/fork/make PRs to improve the experience if they deem it necessary. We hope you do.

**Comment by NetOpWibby** [comment]
I look forward to using this browser without the additional dependency.

**Comment by smcki012** [comment]
Can you comment on your technical concerns and we can surely quell them? Docker is a well known service, everything here is opensource, and there is no access given to Docker beyond the browser’s fullnode/recursive resolver (which is needed for it to access the HNS protocol without a giant pool of dependencies) as we stated above.

**Comment by NetOpWibby** [comment]
My concern isn't about privacy, it's just that to use mainstream browsers you just download and install them. That's it.

If HandyBrowser can work the same way, that'll be a huge improvement.

**Comment by smcki012** [comment]
I respect that and I hope that reservation doesn’t prevent you from atleast giving it a go and leaving feedback/usability related issues or feature requests :). Let’s try to be fair expectations wise for a v0.1.0 release. 😂

**Comment by rafaelcastrocouto** [comment]
I was really hoping to join the project but this dependency just don't allow me to. 
![Untitled](https://user-images.githubusercontent.com/422159/86502397-14731400-bd79-11ea-882e-f8def0db0fa2.png)

**Comment by smcki012** [comment]
> I was really hoping to join the project but this dependency just don't allow me to. 
> 
> ![Untitled](https://user-images.githubusercontent.com/422159/86502397-14731400-bd79-11ea-882e-f8def0db0fa2.png)
> 
> 

Sorry about that, yes the Docker dependency has that OS requirement, so you’ll need to update to be compatible. In the readme and above we stated we’re working to remove that dependency in the future. This is the beta v0.1.0 so please be patient with us. :)
