### ISSUE TITLE
hardcoded wallet addresses

### ISSUE THREAD

**Issue by Thann** [HandyMiner/HandyBrowser#2]
Not really an issue, but more of a question. whats up with the hard-coded addresses like this: https://github.com/HandyMiner/HandyBrowser/blob/master/js/main.js#L74

**Comment by smcki012** [comment]
That’s just something leftover from HandyMiner-GUI for mining fees since the browser was built from that initial GUI we built to abstract the CLI client into a UI prior to launch. Doesn’t affect the browser. That same hardcoded address is used for the donation modal in the app.
