### ISSUE TITLE
Unable to open Handy Browser 

### ISSUE THREAD

**Issue by alexandramedway** [HandyMiner/HandyBrowser#3]
I had Handy Browser opened, then I closed all my applications for the holiday weekend. When I came back and tried to open, I get the following message:
<img width="476" alt="Screen Shot 2020-07-09 at 3 15 52 PM" src="https://user-images.githubusercontent.com/7786527/87081350-3811e080-c1f7-11ea-8549-67263849913a.png">

**Comment by smcki012** [comment]
Yes this is due to the Docker process having closed when your laptop was asleep and suspended. All you have to do is restart if this happens and it'll restore your session as well. Edge case with using a Docker container for the recursive/authoritative/HSD bits.
