### ISSUE TITLE
HNS node not responding

### ISSUE THREAD

**Issue by BeeChains** [HandyMiner/HandyBrowser#4]
Docker is running but start button for docker container does nothing when clicked.

**Comment by smcki012** [comment]
Can you give more details? The install process is as follows:

> Install and run DOCKER, have it open in your menu tray. 
> Double-click the HandyBrowser launcher icon. Wait for the initialization to finish. There is nothing you need to do on the Docker application end. 

Try those steps and let us know your results. And if unsuccessful, please provide more detail.

**Comment by BeeChains** [comment]
Not sure what fixed it but seems like my docker was just stuck . After a lot of restarts Handy Browser is up and HNS node is syncing. On Sat, Jul 18, 2020, 7:05 PM Steven McKie <notifications@github.com> wrote:Can you give more details? The install process is as follows:Install and run DOCKER, have it open in your menu try.Double-click the HandyBrowser launcher icon. Wait for the initialization to finish. There is nothing you need to do on the Docker application end.Try those steps and let us know your results. And if unsuccessfully, please provide more detail.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by BeeChains** [comment]
Laugh for the day, before having issues I was synced know I start back at 4000 or so, I am now at like 6512:24681. However, thank you for the quick response indeed. Sent from Mail for Windows 10 From: Steven McKieSent: Saturday, July 18, 2020 7:05 PMTo: HandyMiner/HandyBrowserCc: BeeChains; AuthorSubject: Re: [HandyMiner/HandyBrowser] HNS node not responding (#4) Can you give more details? The install process is as follows:Install and run DOCKER, have it open in your menu try.Double-click the HandyBrowser launcher icon. Wait for the initialization to finish. There is nothing you need to do on the Docker application end.Try those steps and let us know your results. And if unsuccessfully, please provide more detail.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by BeeChains** [comment]
Node is synced but no luck resolving. Im using NextDNS from namebase https://learn.namebase.io/starting-from-zero/how-to-access-handshake-sites.

**Comment by BeeChains** [comment]
> Can you give more details? The install process is as follows:
> 
> > Install and run DOCKER, have it open in your menu tray.
> > Double-click the HandyBrowser launcher icon. Wait for the initialization to finish. There is nothing you need to do on the Docker application end.
> 
> Try those steps and let us know your results. And if unsuccessful, please provide more detail.

I have to manually start docker but it seems to have been stuck. Restart, delete, rebuild etc. something of the sort got it up and running again, thank you.
