### ISSUE TITLE
Node is synced but no luck resolving. 

### ISSUE THREAD

**Issue by BeeChains** [HandyMiner/HandyBrowser#5]
Node is synced but no luck resolving. Im using NextDNS from namebase https://learn.namebase.io/starting-from-zero/how-to-access-handshake-sites. I have also cleared SSL state for ERR_SSL_protocol and im now getting ERR_TIMED_OUT while trying to resolve google.
_Originally posted by @BeeChains in https://github.com/HandyMiner/HandyBrowser/issues/4#issuecomment-661646800_

**Comment by smcki012** [comment]
Please follow the directions in the Readme install. HandyBrowser is a web browser for HNS that couples HSD and doesn't require NextDNS. Also ensure you're not running Bob wallet and do not have any other Handshake nodes running. 

If you have Docker running, restart it. Then go to run HandyBrowser once more. Closing this issue for the final time.
