### ISSUE TITLE
Optional HNSD

### ISSUE THREAD

**Issue by rafaelcastrocouto** [HandyMiner/HandyBrowser#9]
Is it possible to have an HandyBrowser installation option to avoid using docker and connecting to an external HNSD/HNS resolver? I imagine that most users would not want to run their own node.

Maybe a way to make the node installation more desirable, we could also add an option to add a miner that would work on idle time.

**Comment by smcki012** [comment]
Sorry, no. The Docker dependency is to ensure the browser is usable for the resolver, HSD, and HNSD, without knowing how to setup those utilities. A fully native HNS browser would find a means to incorporate those, and the reference browser's purpose is to ensure anyone who implements HNS in the browser is doing so in a way that secures the network and ensures a user is interacting with the chain in the safest way possible. 

Mining on a device CPU/GPU would be pointless as well with the network difficulty as high as it is, with it now being secured by ASICs. That'd also create unnecessary overhead and confusion from users. If you want to mine I suggest an ASIC miner from Goldshell.com. 

Closing this issue.

**Comment by rafaelcastrocouto** [comment]
Thank you for explaining @smcki012
